version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/iqraa_db
      - DJANGO_SETTINGS_MODULE=iqraa.settings
    volumes:
      - .:/app
    networks:
      - iqraa-network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: iqraa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iqraa-network

volumes:
  postgres_data:

networks:
  iqraa-network:
    driver: bridge