# Generated by Django 5.2 on 2025-04-21 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German')], default='EN', max_length=2)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('page_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='books_title_7a737c_idx'), models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx'), models.Index(fields=['genre'], name='books_genre_d6e4af_idx'), models.Index(fields=['language'], name='books_languag_f5fb51_idx'), models.Index(fields=['is_featured'], name='books_is_feat_73a33b_idx')],
            },
        ),
    ]
